# Generated by Django 5.1.4 on 2025-05-24 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=8)),
                ('sector', models.CharField(choices=[('No Sector', 'No Sector'), ('Media', 'Media'), ('Technology', 'Technology'), ('Real Estate', 'Real Estate'), ('Finance', 'Finance'), ('Utilities', 'Utilities'), ('Healthcare', 'Healthcare'), ('Materials', 'Materials'), ('Industrials', 'Industrials'), ('Consumer Discretionary', 'Consumer Discretionary'), ('Consumer Staples', 'Consumer Staples'), ('Energy', 'Energy')], default='No Sector', max_length=50)),
                ('float', models.CharField(max_length=10)),
                ('trade_period', models.CharField(choices=[('Pre-Market', 'Pre-Market'), ('Intraday', 'Intraday'), ('After Hours', 'After Hours')], max_length=50)),
                ('framework', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1)),
                ('strategy', models.CharField(choices=[('Breakout', 'Breakout'), ('Dip Buy', 'Dip Buy'), ('Gap Up', 'Gap Up'), ('Gap Down', 'Gap Down'), ('Short Sell', 'Short Sell'), ('Supernova', 'Supernova'), ('Swing Trade', 'Swing Trade')], max_length=50)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField()),
                ('result', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
