# Generated by Django 5.1.4 on 2025-02-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeentry',
            name='framework',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='strategy',
            field=models.CharField(choices=[('breakout', 'breakout'), ('dip buy', 'dip buy'), ('gap up', 'gap up'), ('gap down', 'gap down'), ('short sell', 'short sell'), ('supernova', 'supernova'), ('swing trade', 'swing trade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='trade_period',
            field=models.CharField(choices=[('Pre-Market', 'Pre-Market'), ('Intraday', 'Intraday'), ('After Hours', 'After Hours')], max_length=50),
        ),
    ]
