# Generated by Django 5.1.4 on 2025-02-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_journal', '0002_tradeentry_framework_alter_tradeentry_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeentry',
            name='float',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='strategy',
            field=models.CharField(choices=[('breakout', 'Breakout'), ('dip buy', 'Dip Buy'), ('gap up', 'Gap Up'), ('gap down', 'Gap Down'), ('short sell', 'Short Sell'), ('supernova', 'Supernova'), ('swing trade', 'Swing Trade')], max_length=50),
        ),
    ]
