# Generated by Django 5.1.4 on 2025-02-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_journal', '0004_alter_tradeentry_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeentry',
            name='float',
            field=models.CharField(max_length=10),
        ),
    ]
