# Generated by Django 5.1.4 on 2025-03-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_journal', '0006_tradeentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeentry',
            name='sector',
            field=models.CharField(choices=[('no sector', 'No Sector'), ('media', 'Media'), ('technology', 'Technology'), ('real estate', 'Real Estate'), ('finance', 'Finance'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('materials', 'Materials'), ('industrials', 'Industrials'), ('consumer discretionary', 'Consumer Discretionary'), ('consumer staples', 'Consumer Staples'), ('energy', 'Energy')], default='No Sector', max_length=50),
        ),
    ]
