# Generated by Django 5.1.4 on 2025-03-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_journal', '0007_tradeentry_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeentry',
            name='time',
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='date',
            field=models.DateField(),
        ),
    ]
